### ISSUE TITLE
회원가입 불가 현상

### ISSUE THREAD

**Issue by devnine-codes** [dahyeo-n/SPL#37]
안녕하세요! 스플 한번 둘러보려고 하는데 회원가입시 이미지와 같은 가입이 안되는 현상이 있습니다.
혹시 아직 유지보수를 하신다면 확인 한번 부탁드립니다!
![image](https://github.com/user-attachments/assets/8308842c-1200-4a46-a5b7-e1d2a50f9521)

**Comment by dahyeo-n** [comment]
안녕하세요!
헉 감사합니다. 사실 Supabase 유료 플랜 기간이 끝나서 DB 지원을 안 해주는 바람에 생긴 오류입니다..
결제하도록 하겠습니다,, ㅋㅋㅋㅋ 서비스 이용해 주시고, 친절하게 오류 말씀해 주셔서 진심으로 너무 감사합니다 :)

2024년 10월 24일 (목) 오후 6:32, dev-nine ***@***.***>님이 작성:
